use std::fs;
use std::io::{Read, Write};
use std::net::TcpListener;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::sync::{Arc, Mutex};
use std::thread;

use base64::Engine;
use serde_json::{Value, json};
use tempfile::TempDir;

const PUBLIC_KEY: &str = "dW50cnVzdGVkIGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXkgRTc2MjBGMTg0MkI0RTgxRgpSV1FmNkxSQ0dBOWk1M21sWWVjTzRJelQ1MVRHUHB2V3VjTlNDaDFDQk0wUVRhTG43M1k3R0ZPMw==";
const TEST_SIGNATURE: &str = "dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIG1pbmlzaWduIHNlY3JldCBrZXkKUlVRZjZMUkNHQTlpNTU5cjNnN1YxcU55SkRBcEdpcDhNZnFjYWRJZ1Q5Q3VoVjNFTWhIb04xbUdUa1VpZEYvejdTcmxRZ1hkeThvZmpiN2JOSkp5bERPb2NyQ284S0x6WndvPQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNTU2MTkzMzM1CWZpbGU6dGVzdAp5L3JVdzJ5OC9oT1VZalpVNzFlSHAvV28xS1o0MGZHeTJWSkVEbDM0WE1KTStUWDQ4U3MvMTd1M0l2SWZiVlIxRmtaWlNOQ2lzUWJ1UVkrYkh3aEVCZz09";

fn repository_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("repository root")
        .to_path_buf()
}

fn run_powershell(script: &str, arguments: &[&Path]) -> Output {
    let root = repository_root();
    let mut command = Command::new("powershell.exe");
    command
        .args(["-NoProfile", "-ExecutionPolicy", "Bypass", "-File"])
        .arg(root.join(script));
    for argument in arguments {
        command.arg(argument);
    }
    command
        .current_dir(root)
        .output()
        .expect("run PowerShell gate")
}

fn init_release_repository() -> TempDir {
    let temp = TempDir::new().expect("release repository");
    fs::create_dir_all(temp.path().join("src-tauri")).expect("create Tauri directory");
    fs::create_dir_all(temp.path().join("src-tauri/src")).expect("create Rust source directory");
    fs::write(
        temp.path().join("src-tauri/src/lib.rs"),
        "pub fn fixture() {}\n",
    )
    .expect("write Rust source");
    fs::write(
        temp.path().join("package.json"),
        serde_json::to_vec_pretty(&json!({ "name": "fixture", "version": "1.0.0" }))
            .expect("package JSON"),
    )
    .expect("write package.json");
    fs::write(
        temp.path().join("package-lock.json"),
        serde_json::to_vec_pretty(&json!({
            "name": "fixture",
            "version": "1.0.0",
            "lockfileVersion": 3,
            "packages": { "": { "name": "fixture", "version": "1.0.0" } }
        }))
        .expect("lock JSON"),
    )
    .expect("write package-lock.json");
    fs::write(
        temp.path().join("src-tauri/Cargo.toml"),
        "[package]\nname = \"fixture\"\nversion = \"1.0.0\"\nedition = \"2024\"\n",
    )
    .expect("write Cargo.toml");
    fs::write(
        temp.path().join("src-tauri/Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"fixture\"\nversion = \"1.0.0\"\n",
    )
    .expect("write Cargo.lock");
    fs::write(
        temp.path().join("src-tauri/tauri.conf.json"),
        serde_json::to_vec_pretty(&json!({ "productName": "fixture", "version": "1.0.0" }))
            .expect("Tauri JSON"),
    )
    .expect("write Tauri config");

    for arguments in [
        vec!["init", "-b", "main"],
        vec!["config", "user.email", "fixture@example.com"],
        vec!["config", "user.name", "Fixture"],
        vec!["add", "."],
        vec!["commit", "-m", "initial"],
    ] {
        let output = Command::new("git")
            .args(arguments)
            .current_dir(temp.path())
            .output()
            .expect("initialize fixture repository");
        assert!(output.status.success(), "git fixture command failed");
    }
    temp
}

fn read_json(path: impl AsRef<Path>) -> Value {
    serde_json::from_slice(&fs::read(path).expect("read JSON")).expect("parse JSON")
}

fn git_bash() -> PathBuf {
    let output = Command::new("where.exe")
        .arg("bash")
        .output()
        .expect("locate Git Bash");
    assert!(output.status.success());
    String::from_utf8(output.stdout)
        .expect("where output is UTF-8")
        .lines()
        .map(PathBuf::from)
        .find(|path| {
            let normalized = path.to_string_lossy().replace('\\', "/").to_lowercase();
            !normalized.contains("/windows/system32/")
                && !normalized.contains("/microsoft/windowsapps/")
        })
        .expect("Git Bash is installed")
}

#[test]
fn release_prepare_updates_all_versions_from_a_clean_main_repository() {
    let temp = init_release_repository();
    let output = Command::new("powershell.exe")
        .args(["-NoProfile", "-ExecutionPolicy", "Bypass", "-File"])
        .arg(repository_root().join("scripts/prepare-release.ps1"))
        .args(["-Version", "1.2.3", "-Tag", "v1.2.3", "-RepositoryRoot"])
        .arg(temp.path())
        .output()
        .expect("prepare release");

    assert!(
        output.status.success(),
        "release preparation failed: {}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(
        read_json(temp.path().join("package.json"))["version"],
        "1.2.3"
    );
    let lock = read_json(temp.path().join("package-lock.json"));
    assert_eq!(lock["version"], "1.2.3");
    assert_eq!(lock["packages"][""]["version"], "1.2.3");
    assert_eq!(
        read_json(temp.path().join("src-tauri/tauri.conf.json"))["version"],
        "1.2.3"
    );
    assert!(
        fs::read_to_string(temp.path().join("src-tauri/Cargo.toml"))
            .expect("read Cargo manifest")
            .contains("version = \"1.2.3\"")
    );
    assert!(
        fs::read_to_string(temp.path().join("src-tauri/Cargo.lock"))
            .expect("read Cargo lockfile")
            .contains("version = \"1.2.3\"")
    );
}

#[test]
fn release_prepare_rejects_non_semver_dirty_tree_and_mismatched_tag() {
    for (version, tag, dirty) in [
        ("1.2", "v1.2", false),
        ("1.2.3", "v2.0.0", false),
        ("1.2.3", "v1.2.3", true),
    ] {
        let temp = init_release_repository();
        if dirty {
            fs::write(temp.path().join("dirty.txt"), "dirty\n").expect("dirty fixture");
        }
        let output = Command::new("powershell.exe")
            .args(["-NoProfile", "-ExecutionPolicy", "Bypass", "-File"])
            .arg(repository_root().join("scripts/prepare-release.ps1"))
            .args(["-Version", version, "-Tag", tag, "-RepositoryRoot"])
            .arg(temp.path())
            .output()
            .expect("reject release preparation");
        assert!(
            !output.status.success(),
            "invalid release preparation passed"
        );
    }
}

#[test]
fn updater_manifest_gate_accepts_only_complete_windows_stable_entries() {
    let temp = TempDir::new().expect("manifest fixture");
    let valid = temp.path().join("valid.json");
    fs::write(
        &valid,
        serde_json::to_vec_pretty(&json!({
            "version": "1.2.3",
            "notes": "正式版本",
            "pub_date": "2026-08-18T00:00:00Z",
            "platforms": {
                "windows-x86_64": {
                    "url": "https://gitcode.com/example/releases/download/v1.2.3/GPTEasy.exe",
                    "signature": TEST_SIGNATURE
                }
            }
        }))
        .expect("manifest JSON"),
    )
    .expect("write manifest");
    let output = run_powershell(
        "scripts/test-updater-manifest.ps1",
        &[Path::new("-ManifestPath"), &valid],
    );
    assert!(
        output.status.success(),
        "valid updater manifest failed: {}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );

    for (name, manifest) in [
        (
            "prerelease.json",
            json!({
                "version": "1.2.3-beta.1",
                "platforms": { "windows-x86_64": { "url": "https://example.com/a.exe", "signature": TEST_SIGNATURE } }
            }),
        ),
        (
            "missing-signature.json",
            json!({
                "version": "1.2.3",
                "platforms": { "windows-x86_64": { "url": "https://example.com/a.exe" } }
            }),
        ),
        (
            "http.json",
            json!({
                "version": "1.2.3",
                "platforms": { "windows-x86_64": { "url": "http://example.com/a.exe", "signature": TEST_SIGNATURE } }
            }),
        ),
    ] {
        let path = temp.path().join(name);
        fs::write(
            &path,
            serde_json::to_vec_pretty(&manifest).expect("invalid manifest JSON"),
        )
        .expect("write invalid manifest");
        let output = run_powershell(
            "scripts/test-updater-manifest.ps1",
            &[Path::new("-ManifestPath"), &path],
        );
        assert!(!output.status.success(), "invalid manifest passed: {name}");
    }
}

#[test]
fn updater_signature_verifier_rejects_changed_artifact() {
    let temp = TempDir::new().expect("signature fixture");
    let artifact = temp.path().join("artifact.bin");
    let signature = temp.path().join("artifact.bin.sig");
    fs::write(&artifact, b"test").expect("write signed artifact");
    fs::write(&signature, TEST_SIGNATURE).expect("write updater signature");

    let run = |artifact: &Path| {
        Command::new("cargo")
            .args([
                "run",
                "--quiet",
                "--manifest-path",
                "src-tauri/Cargo.toml",
                "--example",
                "verify_updater_signature",
                "--",
            ])
            .arg(artifact)
            .arg(&signature)
            .arg(PUBLIC_KEY)
            .current_dir(repository_root())
            .output()
            .expect("run updater signature verifier")
    };

    let valid = run(&artifact);
    assert!(
        valid.status.success(),
        "valid signature failed: {}",
        String::from_utf8_lossy(&valid.stderr)
    );
    fs::write(&artifact, b"changed").expect("change signed artifact");
    assert!(
        !run(&artifact).status.success(),
        "changed artifact passed signature gate"
    );
}

#[test]
fn trust_root_gate_allows_only_public_inputs_and_rejects_tracked_private_keys() {
    let temp = TempDir::new().expect("trust root fixture");
    fs::create_dir_all(temp.path().join("src-tauri")).expect("create Tauri directory");
    fs::create_dir_all(temp.path().join(".github/workflows")).expect("create workflow directory");
    fs::create_dir_all(temp.path().join("scripts")).expect("create script directory");
    fs::write(
        temp.path().join("scripts/gitcode-distribution.json"),
        serde_json::to_vec_pretty(&json!({
            "schemaVersion": 1,
            "issue": 41,
            "apiBaseUrl": "https://api.gitcode.com/api/v5",
            "rawBaseUrl": "https://raw.gitcode.com",
            "defaultBranch": "main",
            "formalManifestPath": "latest.md",
            "smokeManifestPrefix": "smoke/",
            "platform": "windows-x86_64",
            "repositoryVariable": "GITCODE_REPOSITORY",
            "branchVariable": "GITCODE_DEFAULT_BRANCH",
            "tokenSecret": "GITCODE_TOKEN"
        }))
        .expect("distribution contract JSON"),
    )
    .expect("write distribution contract");
    fs::write(
        temp.path().join("src-tauri/tauri.conf.json"),
        serde_json::to_vec_pretty(&json!({
            "bundle": { "createUpdaterArtifacts": true },
            "plugins": {
                "updater": {
                    "endpoints": ["https://raw.gitcode.com/example/releases/raw/main/latest.md"],
                    "pubkey": PUBLIC_KEY
                }
            }
        }))
        .expect("Tauri trust root JSON"),
    )
    .expect("write Tauri trust root");
    fs::write(
        temp.path().join(".github/workflows/gitcode-smoke.yml"),
        "env:\n  GITCODE_TOKEN: ${{ secrets.GITCODE_TOKEN }}\n  GITCODE_REPOSITORY: ${{ vars.GITCODE_REPOSITORY }}\n",
    )
    .expect("write workflow");
    fs::write(
        temp.path().join(".github/workflows/gitcode-sync.yml"),
        "on:\n  release:\n    types: [published]\nenv:\n  GITCODE_TOKEN: ${{ secrets.GITCODE_TOKEN }}\n  GITCODE_REPOSITORY: ${{ vars.GITCODE_REPOSITORY }}\n",
    )
    .expect("write sync workflow");
    fs::write(
        temp.path().join("scripts/smoke-gitcode-release.sh"),
        "#!/usr/bin/env bash\n# gitcode-distribution.json\nAuthorization: Bearer $GITCODE_TOKEN\n",
    )
    .expect("write smoke script");
    fs::write(
        temp.path().join("scripts/sync-gitcode-release.mjs"),
        "const headers = { Authorization: `Bearer ${configuration.gitcodeToken}` };\n",
    )
    .expect("write sync script");
    fs::write(
        temp.path().join("scripts/setup-gitcode-distribution.sh"),
        "#!/usr/bin/env bash\nask_secret GITCODE_TOKEN\nset_secret \"$TOKEN_SECRET_NAME\"\nunset GITCODE_TOKEN\n",
    )
    .expect("write setup wizard");
    let init = Command::new("git")
        .args(["init", "-b", "main"])
        .current_dir(temp.path())
        .output()
        .expect("initialize trust root repository");
    assert!(init.status.success());
    let add = Command::new("git")
        .args(["add", "."])
        .current_dir(temp.path())
        .output()
        .expect("track public trust inputs");
    assert!(add.status.success());

    let run = || {
        run_powershell(
            "scripts/test-update-trust-root.ps1",
            &[Path::new("-RepositoryRoot"), temp.path()],
        )
    };
    let public_only = run();
    assert!(
        public_only.status.success(),
        "public trust root failed: {}{}",
        String::from_utf8_lossy(&public_only.stdout),
        String::from_utf8_lossy(&public_only.stderr)
    );

    let private_key_fixture = base64::engine::general_purpose::STANDARD.encode(format!(
        "untrusted comment: tauri signer {} secret key\nfixture-only\n",
        "encrypted"
    ));
    fs::write(temp.path().join("renamed.txt"), private_key_fixture)
        .expect("write disguised private key");
    let add = Command::new("git")
        .args(["add", "renamed.txt"])
        .current_dir(temp.path())
        .output()
        .expect("track leaked private key");
    assert!(add.status.success());
    assert!(
        !run().status.success(),
        "tracked updater private key passed gate"
    );
}

#[test]
fn configure_trust_root_writes_only_public_endpoint_and_key() {
    let temp = TempDir::new().expect("configuration fixture");
    fs::create_dir_all(temp.path().join("src-tauri")).expect("create Tauri directory");
    fs::write(
        temp.path().join("src-tauri/tauri.conf.json"),
        serde_json::to_vec_pretty(&json!({
            "productName": "fixture",
            "bundle": { "active": true }
        }))
        .expect("Tauri fixture JSON"),
    )
    .expect("write Tauri fixture");
    let output = Command::new("node")
        .arg(repository_root().join("scripts/configure-update-trust-root.mjs"))
        .args(["example/releases", PUBLIC_KEY, "--repository-root"])
        .arg(temp.path())
        .output()
        .expect("configure update trust root");
    assert!(
        output.status.success(),
        "trust root configuration failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let config = read_json(temp.path().join("src-tauri/tauri.conf.json"));
    assert_eq!(config["bundle"]["createUpdaterArtifacts"], true);
    assert_eq!(config["plugins"]["updater"]["pubkey"], PUBLIC_KEY);
    assert_eq!(
        config["plugins"]["updater"]["endpoints"],
        json!(["https://raw.gitcode.com/example/releases/raw/main/latest.md"])
    );
    let serialized = serde_json::to_string(&config).expect("serialize configured trust root");
    assert!(!serialized.contains("GITCODE_TOKEN"));
    assert!(!serialized.contains("PRIVATE_KEY"));
}

#[test]
fn configure_trust_root_accepts_the_current_tauri_public_key_header() {
    let temp = TempDir::new().expect("current Tauri public key fixture");
    fs::create_dir_all(temp.path().join("src-tauri")).expect("create Tauri directory");
    fs::write(
        temp.path().join("src-tauri/tauri.conf.json"),
        "{\"bundle\":{}}\n",
    )
    .expect("write Tauri config");
    let decoded = String::from_utf8(
        base64::engine::general_purpose::STANDARD
            .decode(PUBLIC_KEY)
            .expect("decode public key fixture"),
    )
    .expect("public key fixture UTF-8");
    let payload = decoded.lines().nth(1).expect("public key payload");
    let current_tauri_key = base64::engine::general_purpose::STANDARD.encode(format!(
        "untrusted comment: minisign public key: FIXTURE\n{payload}"
    ));
    let output = Command::new("node")
        .arg(repository_root().join("scripts/configure-update-trust-root.mjs"))
        .args(["example/releases", &current_tauri_key, "--repository-root"])
        .arg(temp.path())
        .output()
        .expect("configure current Tauri public key");
    assert!(
        output.status.success(),
        "current Tauri public key was rejected: {}",
        String::from_utf8_lossy(&output.stderr)
    );
}

#[test]
fn windows_candidate_requires_and_verifies_the_updater_signature() {
    let script = fs::read_to_string(repository_root().join("scripts/build-windows-candidate.ps1"))
        .expect("read Windows candidate builder");
    assert!(script.contains("TAURI_SIGNING_PRIVATE_KEY_PASSWORD"));
    assert!(script.contains("scripts/test-update-trust-root.ps1"));
    assert!(script.contains("verify_updater_signature"));
    assert!(script.contains("updaterSignature = 'passed'"));
    assert!(script.contains("signaturePath"));
    assert!(!script.contains("$env:TAURI_SIGNING_PRIVATE_KEY ="));
    assert!(script.contains("Remove-Item Env:TAURI_SIGNING_PRIVATE_KEY"));
}

#[test]
fn encrypted_updater_key_check_understands_the_current_tauri_header() {
    let temp = TempDir::new().expect("updater key fixture");
    let encrypted = temp.path().join("encrypted.key");
    let unencrypted = temp.path().join("unencrypted.key");
    let encode = |value: &str| base64::engine::general_purpose::STANDARD.encode(value);
    fs::write(
        &encrypted,
        encode("untrusted comment: tauri signer encrypted secret key\nfixture-only\n"),
    )
    .expect("write encrypted key fixture");
    fs::write(
        &unencrypted,
        encode("untrusted comment: tauri signer secret key\nfixture-only\n"),
    )
    .expect("write unencrypted key fixture");

    let run = |path: &Path| {
        Command::new("node")
            .arg(repository_root().join("scripts/check-encrypted-updater-key.mjs"))
            .arg(path)
            .output()
            .expect("check encrypted updater key")
    };
    let encrypted_result = run(&encrypted);
    assert!(encrypted_result.status.success());
    let report: Value =
        serde_json::from_slice(&encrypted_result.stdout).expect("encrypted key report");
    assert_eq!(report, json!({ "encrypted": true }));
    assert!(!run(&unencrypted).status.success());
}

#[test]
fn repository_declares_repeatable_gitcode_setup_without_formal_smoke_manifest_writes() {
    let root = repository_root();
    let wizard = fs::read_to_string(root.join("scripts/setup-gitcode-distribution.sh"))
        .expect("read GitCode setup wizard");
    let contract = read_json(root.join("scripts/gitcode-distribution.json"));
    let token_secret = contract["tokenSecret"].as_str().expect("token secret name");
    let repository_variable = contract["repositoryVariable"]
        .as_str()
        .expect("repository variable name");
    let branch_variable = contract["branchVariable"]
        .as_str()
        .expect("branch variable name");
    assert!(wizard.contains("ask_secret GITCODE_TOKEN"));
    assert!(wizard.contains("set_secret \"$TOKEN_SECRET_NAME\""));
    assert!(wizard.contains("set_var \"$REPOSITORY_VARIABLE_NAME\""));
    assert!(wizard.contains("set_var \"$BRANCH_VARIABLE_NAME\""));
    assert_eq!(token_secret, "GITCODE_TOKEN");
    assert_eq!(repository_variable, "GITCODE_REPOSITORY");
    assert_eq!(branch_variable, "GITCODE_DEFAULT_BRANCH");
    assert!(wizard.contains("离线备份"));
    assert_eq!(wizard.matches("ask_secret GITCODE_TOKEN").count(), 1);
    assert!(wizard.contains("gh workflow run gitcode-smoke.yml"));

    let workflow = fs::read_to_string(root.join(".github/workflows/gitcode-smoke.yml"))
        .expect("read GitCode smoke workflow");
    assert!(workflow.contains("GITCODE_TOKEN: ${{ secrets.GITCODE_TOKEN }}"));
    assert!(workflow.contains("GITCODE_REPOSITORY: ${{ vars.GITCODE_REPOSITORY }}"));

    let smoke = fs::read_to_string(root.join("scripts/smoke-gitcode-release.sh"))
        .expect("read GitCode smoke command");
    assert!(smoke.contains("smoke-"));
    assert!(!smoke.contains("latest.md"));
}

#[test]
fn gitcode_distribution_contract_contains_only_public_protocol_configuration() {
    let contract = read_json(repository_root().join("scripts/gitcode-distribution.json"));
    assert_eq!(contract["schemaVersion"], 1);
    assert_eq!(contract["issue"], 41);
    assert_eq!(contract["apiBaseUrl"], "https://api.gitcode.com/api/v5");
    assert_eq!(contract["rawBaseUrl"], "https://raw.gitcode.com");
    assert_eq!(contract["formalManifestPath"], "latest.md");
    assert_eq!(contract["smokeManifestPrefix"], "smoke/");
    assert_eq!(contract["platform"], "windows-x86_64");
    assert_eq!(contract["repositoryVariable"], "GITCODE_REPOSITORY");
    assert_eq!(contract["branchVariable"], "GITCODE_DEFAULT_BRANCH");
    assert_eq!(contract["tokenSecret"], "GITCODE_TOKEN");
    let serialized = serde_json::to_string(&contract).expect("serialize GitCode contract");
    assert!(!serialized.contains("Bearer "));
    assert!(!serialized.contains("PRIVATE_KEY"));
    assert!(!serialized.contains("PASSWORD"));
}

#[test]
fn gitcode_smoke_exercises_authenticated_writes_and_anonymous_reads() {
    #[derive(Debug)]
    struct RequestRecord {
        method: String,
        path: String,
        authorization: Option<String>,
        upload_test_header: Option<String>,
    }

    let listener = TcpListener::bind("127.0.0.1:0").expect("bind fake GitCode server");
    let address = listener.local_addr().expect("fake GitCode address");
    let records = Arc::new(Mutex::new(Vec::<RequestRecord>::new()));
    let server_records = Arc::clone(&records);
    let server = thread::spawn(move || {
        let mut raw_manifest = String::new();
        let mut attachment_downloads = 0;
        let mut raw_downloads = 0;
        for _ in 0..9 {
            let (mut stream, _) = listener.accept().expect("accept fake GitCode request");
            let mut request = Vec::new();
            let mut buffer = [0_u8; 8192];
            let header_end;
            loop {
                let read = stream.read(&mut buffer).expect("read fake request");
                assert!(read > 0, "request closed before headers");
                request.extend_from_slice(&buffer[..read]);
                if let Some(index) = request.windows(4).position(|window| window == b"\r\n\r\n") {
                    header_end = index + 4;
                    break;
                }
            }
            let headers = String::from_utf8_lossy(&request[..header_end]).into_owned();
            let content_length = headers
                .lines()
                .find_map(|line| {
                    line.strip_prefix("Content-Length: ")
                        .or_else(|| line.strip_prefix("content-length: "))
                })
                .and_then(|value| value.trim().parse::<usize>().ok())
                .unwrap_or(0);
            while request.len() < header_end + content_length {
                let read = stream.read(&mut buffer).expect("read fake request body");
                assert!(read > 0, "request closed before body");
                request.extend_from_slice(&buffer[..read]);
            }
            let request_line = headers.lines().next().expect("request line");
            let mut request_parts = request_line.split_whitespace();
            let method = request_parts.next().expect("request method").to_owned();
            let path = request_parts.next().expect("request path").to_owned();
            let authorization = headers.lines().find_map(|line| {
                line.strip_prefix("Authorization: ")
                    .or_else(|| line.strip_prefix("authorization: "))
                    .map(str::to_owned)
            });
            let upload_test_header = headers.lines().find_map(|line| {
                line.strip_prefix("x-upload-test: ")
                    .or_else(|| line.strip_prefix("X-Upload-Test: "))
                    .map(str::to_owned)
            });
            server_records
                .lock()
                .expect("request records")
                .push(RequestRecord {
                    method: method.clone(),
                    path: path.clone(),
                    authorization,
                    upload_test_header,
                });

            let (status, content_type, response) = if method == "POST"
                && path.ends_with("/releases")
            {
                (201, "application/json", "{}".to_owned())
            } else if method == "GET"
                && path.contains("/upload_url?file_name=gpteasy-smoke-42-1.txt")
            {
                (
                    200,
                    "application/json",
                    format!(
                        "{{\"url\":\"http://{address}/upload\",\"headers\":{{\"x-upload-test\":\"fixture\"}}}}"
                    ),
                )
            } else if method == "PUT" && path == "/upload" {
                (201, "application/json", "{}".to_owned())
            } else if method == "GET" && path.ends_with("/download") {
                attachment_downloads += 1;
                if attachment_downloads == 1 {
                    (418, "text/plain", "not propagated".to_owned())
                } else {
                    (
                        200,
                        "text/plain",
                        "GPTEasy GitCode distribution smoke smoke-42-1\n".to_owned(),
                    )
                }
            } else if method == "POST" && path.contains("/contents/smoke/") {
                let body = &request[header_end..header_end + content_length];
                let content: Value = serde_json::from_slice(body).expect("content request JSON");
                let decoded = base64::engine::general_purpose::STANDARD
                    .decode(content["content"].as_str().expect("base64 content"))
                    .expect("decode test manifest");
                raw_manifest = String::from_utf8(decoded).expect("test manifest UTF-8");
                (201, "application/json", "{}".to_owned())
            } else if method == "GET"
                && path.contains("/contents/smoke/")
                && path.ends_with("?ref=main")
            {
                (
                    200,
                    "application/json",
                    format!(
                        "{{\"download_url\":\"http://{address}/raw/blobs/fixture/smoke/smoke-42-1.md\"}}"
                    ),
                )
            } else if method == "GET" && path.starts_with("/raw/blobs/") {
                raw_downloads += 1;
                if raw_downloads == 1 {
                    (403, "text/plain", "not propagated".to_owned())
                } else {
                    (200, "application/json", raw_manifest.clone())
                }
            } else {
                (
                    404,
                    "application/json",
                    "{\"message\":\"not found\"}".to_owned(),
                )
            };
            let reason = match status {
                200 => "OK",
                201 => "Created",
                403 => "Forbidden",
                418 => "I'm a teapot",
                _ => "Not Found",
            };
            write!(
                stream,
                "HTTP/1.1 {status} {reason}\r\nContent-Type: {content_type}\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{response}",
                response.len()
            )
            .expect("write fake response");
        }
    });

    let output = Command::new(git_bash())
        .arg("scripts/smoke-gitcode-release.sh")
        .env("GITCODE_TOKEN", "test-token")
        .env("GITCODE_REPOSITORY", "example/releases")
        .env("GITCODE_DEFAULT_BRANCH", "main")
        .env("SMOKE_RUN_ID", "42-1")
        .env("GITCODE_SMOKE_TEST_MODE", "1")
        .env("GITCODE_API_BASE_URL", format!("http://{address}/api/v5"))
        .env("GITCODE_RAW_BASE_URL", format!("http://{address}/raw"))
        .env("GITCODE_SMOKE_RETRY_DELAY_SECONDS", "0")
        .current_dir(repository_root())
        .output()
        .expect("run GitCode smoke against fake server");
    assert!(
        output.status.success(),
        "GitCode smoke failed: {}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    server.join().expect("fake GitCode server");
    let report: Value = serde_json::from_slice(&output.stdout).expect("smoke report JSON");
    assert_eq!(report["passed"], true);
    assert_eq!(report["formalManifestAdvanced"], false);

    let records = records.lock().expect("read request records");
    assert_eq!(records.len(), 9);
    assert!(
        records
            .iter()
            .all(|record| !record.path.contains("latest.md"))
    );
    for record in records.iter() {
        let authenticated = record.path.starts_with("/api/v5/")
            && !record.path.ends_with("/download")
            && !(record.method == "GET" && record.path.contains("/contents/smoke/"));
        if authenticated {
            assert_eq!(record.authorization.as_deref(), Some("Bearer test-token"));
        } else {
            assert_eq!(record.authorization, None);
        }
    }
    assert_eq!(records[0].method, "POST");
    assert_eq!(records[2].method, "PUT");
    assert_eq!(records[2].upload_test_header.as_deref(), Some("fixture"));
    assert_eq!(records[8].method, "GET");
}
