use std::fs;
use std::io::{Read, Write};
use std::net::TcpListener;
use std::path::{Path, PathBuf};
use std::process::{Command, Output, Stdio};
use std::sync::{Arc, Mutex};
use std::thread;
use std::time::{Duration, Instant};

use base64::Engine;
use serde_json::{Value, json};
use sha2::{Digest, Sha256};
use tempfile::TempDir;

const PUBLIC_KEY: &str = "dW50cnVzdGVkIGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXkgRTc2MjBGMTg0MkI0RTgxRgpSV1FmNkxSQ0dBOWk1M21sWWVjTzRJelQ1MVRHUHB2V3VjTlNDaDFDQk0wUVRhTG43M1k3R0ZPMw==";
const TEST_SIGNATURE: &str = "dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIG1pbmlzaWduIHNlY3JldCBrZXkKUlVRZjZMUkNHQTlpNTU5cjNnN1YxcU55SkRBcEdpcDhNZnFjYWRJZ1Q5Q3VoVjNFTWhIb04xbUdUa1VpZEYvejdTcmxRZ1hkeThvZmpiN2JOSkp5bERPb2NyQ284S0x6WndvPQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNTU2MTkzMzM1CWZpbGU6dGVzdAp5L3JVdzJ5OC9oT1VZalpVNzFlSHAvV28xS1o0MGZHeTJWSkVEbDM0WE1KTStUWDQ4U3MvMTd1M0l2SWZiVlIxRmtaWlNOQ2lzUWJ1UVkrYkh3aEVCZz09";

fn repository_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("repository root")
        .to_path_buf()
}

fn run_powershell(script: &str, arguments: &[&Path]) -> Output {
    let root = repository_root();
    let mut command = Command::new("powershell.exe");
    command
        .args(["-NoProfile", "-ExecutionPolicy", "Bypass", "-File"])
        .arg(root.join(script));
    for argument in arguments {
        command.arg(argument);
    }
    command
        .current_dir(root)
        .output()
        .expect("run PowerShell gate")
}

fn init_release_repository() -> TempDir {
    let temp = TempDir::new().expect("release repository");
    fs::create_dir_all(temp.path().join("src-tauri")).expect("create Tauri directory");
    fs::create_dir_all(temp.path().join("src-tauri/src")).expect("create Rust source directory");
    fs::write(
        temp.path().join("src-tauri/src/lib.rs"),
        "pub fn fixture() {}\n",
    )
    .expect("write Rust source");
    fs::write(
        temp.path().join("package.json"),
        serde_json::to_vec_pretty(&json!({ "name": "fixture", "version": "1.0.0" }))
            .expect("package JSON"),
    )
    .expect("write package.json");
    fs::write(
        temp.path().join("package-lock.json"),
        serde_json::to_vec_pretty(&json!({
            "name": "fixture",
            "version": "1.0.0",
            "lockfileVersion": 3,
            "packages": { "": { "name": "fixture", "version": "1.0.0" } }
        }))
        .expect("lock JSON"),
    )
    .expect("write package-lock.json");
    fs::write(
        temp.path().join("src-tauri/Cargo.toml"),
        "[package]\nname = \"fixture\"\nversion = \"1.0.0\"\nedition = \"2024\"\n",
    )
    .expect("write Cargo.toml");
    fs::write(
        temp.path().join("src-tauri/Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"fixture\"\nversion = \"1.0.0\"\n",
    )
    .expect("write Cargo.lock");
    fs::write(
        temp.path().join("src-tauri/tauri.conf.json"),
        serde_json::to_vec_pretty(&json!({ "productName": "fixture", "version": "1.0.0" }))
            .expect("Tauri JSON"),
    )
    .expect("write Tauri config");

    for arguments in [
        vec!["init", "-b", "main"],
        vec!["config", "user.email", "fixture@example.com"],
        vec!["config", "user.name", "Fixture"],
        vec!["add", "."],
        vec!["commit", "-m", "initial"],
    ] {
        let output = Command::new("git")
            .args(arguments)
            .current_dir(temp.path())
            .output()
            .expect("initialize fixture repository");
        assert!(output.status.success(), "git fixture command failed");
    }
    temp
}

fn create_trust_root_fixture() -> TempDir {
    let temp = TempDir::new().expect("trust root fixture");
    fs::create_dir_all(temp.path().join("src-tauri")).expect("create Tauri directory");
    fs::create_dir_all(temp.path().join(".github/workflows")).expect("create workflow directory");
    fs::create_dir_all(temp.path().join("scripts")).expect("create script directory");
    fs::write(
        temp.path().join("scripts/gitee-distribution.json"),
        serde_json::to_vec_pretty(&json!({
            "schemaVersion": 1,
            "issue": 55,
            "apiBaseUrl": "https://api.gitee.com/api/v5",
            "rawBaseUrl": "https://gitee.com",
            "defaultBranch": "main",
            "formalManifestPath": "latest.md",
            "smokeManifestPrefix": "smoke/",
            "platform": "windows-x86_64",
            "repositoryVariable": "GITEE_REPOSITORY",
            "branchVariable": "GITEE_DEFAULT_BRANCH",
            "tokenSecret": "GITEE_TOKEN"
        }))
        .expect("distribution contract JSON"),
    )
    .expect("write distribution contract");
    fs::write(
        temp.path().join("src-tauri/tauri.conf.json"),
        serde_json::to_vec_pretty(&json!({
            "bundle": { "createUpdaterArtifacts": true },
            "plugins": {
                "updater": {
                    "endpoints": ["https://gitee.com/ericshaohua/gpteasy-releases/raw/main/latest.md"],
                    "pubkey": PUBLIC_KEY
                }
            }
        }))
        .expect("Tauri trust root JSON"),
    )
    .expect("write Tauri trust root");
    for (path, content) in [
        (
            ".github/workflows/gitee-smoke.yml",
            "GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}\nGITEE_REPOSITORY: ${{ vars.GITEE_REPOSITORY }}\n",
        ),
        (
            ".github/workflows/gitee-sync.yml",
            "types: [published]\nGITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}\nGITEE_REPOSITORY: ${{ vars.GITEE_REPOSITORY }}\n",
        ),
        (
            "scripts/smoke-gitee-release.sh",
            "gitee-distribution.json\nAuthorization: Bearer $GITEE_TOKEN\n--range 0-0\nprerelease=true\ntarget_commitish=$GITEE_DEFAULT_BRANCH\n",
        ),
        (
            "scripts/sync-gitee-release.mjs",
            "Authorization: `Bearer ${configuration.giteeToken}`\nspawn(\"curl\", [\n\"--form\"\nnew URLSearchParams()\nnumericReleaseId()\ntarget_commitish: config.giteeBranch\n",
        ),
        (
            "scripts/setup-gitee-distribution.sh",
            "ask_secret GITEE_TOKEN\nset_secret \"$TOKEN_SECRET_NAME\"\nunset GITEE_TOKEN\n",
        ),
    ] {
        fs::write(temp.path().join(path), content).expect("write trust root dependency");
    }
    for arguments in [vec!["init", "-b", "main"], vec!["add", "."]] {
        let output = Command::new("git")
            .args(arguments)
            .current_dir(temp.path())
            .output()
            .expect("initialize trust root repository");
        assert!(output.status.success());
    }
    temp
}

fn read_json(path: impl AsRef<Path>) -> Value {
    serde_json::from_slice(&fs::read(path).expect("read JSON")).expect("parse JSON")
}

fn git_bash() -> PathBuf {
    let output = Command::new("where.exe")
        .arg("bash")
        .output()
        .expect("locate Git Bash");
    assert!(output.status.success());
    String::from_utf8(output.stdout)
        .expect("where output is UTF-8")
        .lines()
        .map(PathBuf::from)
        .find(|path| {
            let normalized = path.to_string_lossy().replace('\\', "/").to_lowercase();
            !normalized.contains("/windows/system32/")
                && !normalized.contains("/microsoft/windowsapps/")
        })
        .expect("Git Bash is installed")
}

#[test]
fn release_prepare_updates_all_versions_from_a_clean_main_repository() {
    let temp = init_release_repository();
    let output = Command::new("powershell.exe")
        .args(["-NoProfile", "-ExecutionPolicy", "Bypass", "-File"])
        .arg(repository_root().join("scripts/prepare-release.ps1"))
        .args(["-Version", "1.2.3", "-Tag", "v1.2.3", "-RepositoryRoot"])
        .arg(temp.path())
        .output()
        .expect("prepare release");

    assert!(
        output.status.success(),
        "release preparation failed: {}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(
        read_json(temp.path().join("package.json"))["version"],
        "1.2.3"
    );
    let lock = read_json(temp.path().join("package-lock.json"));
    assert_eq!(lock["version"], "1.2.3");
    assert_eq!(lock["packages"][""]["version"], "1.2.3");
    assert_eq!(
        read_json(temp.path().join("src-tauri/tauri.conf.json"))["version"],
        "1.2.3"
    );
    assert!(
        fs::read_to_string(temp.path().join("src-tauri/Cargo.toml"))
            .expect("read Cargo manifest")
            .contains("version = \"1.2.3\"")
    );
    assert!(
        fs::read_to_string(temp.path().join("src-tauri/Cargo.lock"))
            .expect("read Cargo lockfile")
            .contains("version = \"1.2.3\"")
    );
}

#[test]
fn release_prepare_rejects_non_semver_dirty_tree_and_mismatched_tag() {
    for (version, tag, dirty) in [
        ("1.2", "v1.2", false),
        ("1.2.3", "v2.0.0", false),
        ("1.2.3", "v1.2.3", true),
    ] {
        let temp = init_release_repository();
        if dirty {
            fs::write(temp.path().join("dirty.txt"), "dirty\n").expect("dirty fixture");
        }
        let output = Command::new("powershell.exe")
            .args(["-NoProfile", "-ExecutionPolicy", "Bypass", "-File"])
            .arg(repository_root().join("scripts/prepare-release.ps1"))
            .args(["-Version", version, "-Tag", tag, "-RepositoryRoot"])
            .arg(temp.path())
            .output()
            .expect("reject release preparation");
        assert!(
            !output.status.success(),
            "invalid release preparation passed"
        );
    }
}

#[test]
fn updater_manifest_gate_accepts_only_complete_windows_stable_entries() {
    let temp = TempDir::new().expect("manifest fixture");
    let valid = temp.path().join("valid.json");
    fs::write(
        &valid,
        serde_json::to_vec_pretty(&json!({
            "version": "1.2.3",
            "notes": "正式版本",
            "pub_date": "2026-08-18T00:00:00Z",
            "platforms": {
                "windows-x86_64": {
                    "url": "https://gitee.com/example/releases/download/v1.2.3/GPTEasy.exe",
                    "signature": TEST_SIGNATURE
                }
            }
        }))
        .expect("manifest JSON"),
    )
    .expect("write manifest");
    let output = run_powershell(
        "scripts/test-updater-manifest.ps1",
        &[Path::new("-ManifestPath"), &valid],
    );
    assert!(
        output.status.success(),
        "valid updater manifest failed: {}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );

    for (name, manifest) in [
        (
            "prerelease.json",
            json!({
                "version": "1.2.3-beta.1",
                "platforms": { "windows-x86_64": { "url": "https://example.com/a.exe", "signature": TEST_SIGNATURE } }
            }),
        ),
        (
            "missing-signature.json",
            json!({
                "version": "1.2.3",
                "platforms": { "windows-x86_64": { "url": "https://example.com/a.exe" } }
            }),
        ),
        (
            "http.json",
            json!({
                "version": "1.2.3",
                "platforms": { "windows-x86_64": { "url": "http://example.com/a.exe", "signature": TEST_SIGNATURE } }
            }),
        ),
    ] {
        let path = temp.path().join(name);
        fs::write(
            &path,
            serde_json::to_vec_pretty(&manifest).expect("invalid manifest JSON"),
        )
        .expect("write invalid manifest");
        let output = run_powershell(
            "scripts/test-updater-manifest.ps1",
            &[Path::new("-ManifestPath"), &path],
        );
        assert!(!output.status.success(), "invalid manifest passed: {name}");
    }
}

#[test]
fn updater_signature_verifier_rejects_changed_artifact() {
    let temp = TempDir::new().expect("signature fixture");
    let artifact = temp.path().join("artifact.bin");
    let signature = temp.path().join("artifact.bin.sig");
    fs::write(&artifact, b"test").expect("write signed artifact");
    fs::write(&signature, TEST_SIGNATURE).expect("write updater signature");

    let run = |artifact: &Path| {
        Command::new("cargo")
            .args([
                "run",
                "--quiet",
                "--manifest-path",
                "src-tauri/Cargo.toml",
                "--example",
                "verify_updater_signature",
                "--",
            ])
            .arg(artifact)
            .arg(&signature)
            .arg(PUBLIC_KEY)
            .current_dir(repository_root())
            .output()
            .expect("run updater signature verifier")
    };

    let valid = run(&artifact);
    assert!(
        valid.status.success(),
        "valid signature failed: {}",
        String::from_utf8_lossy(&valid.stderr)
    );
    fs::write(&artifact, b"changed").expect("change signed artifact");
    assert!(
        !run(&artifact).status.success(),
        "changed artifact passed signature gate"
    );
}

#[test]
fn trust_root_gate_allows_only_public_inputs_and_rejects_tracked_private_keys() {
    let temp = create_trust_root_fixture();

    let run = || {
        run_powershell(
            "scripts/test-update-trust-root.ps1",
            &[Path::new("-RepositoryRoot"), temp.path()],
        )
    };
    let public_only = run();
    assert!(
        public_only.status.success(),
        "public trust root failed: {}{}",
        String::from_utf8_lossy(&public_only.stdout),
        String::from_utf8_lossy(&public_only.stderr)
    );

    let private_key_fixture = base64::engine::general_purpose::STANDARD.encode(format!(
        "untrusted comment: tauri signer {} secret key\nfixture-only\n",
        "encrypted"
    ));
    fs::write(temp.path().join("renamed.txt"), private_key_fixture)
        .expect("write disguised private key");
    let add = Command::new("git")
        .args(["add", "renamed.txt"])
        .current_dir(temp.path())
        .output()
        .expect("track leaked private key");
    assert!(add.status.success());
    assert!(
        !run().status.success(),
        "tracked updater private key passed gate"
    );
}

#[test]
fn trust_root_gate_rejects_any_endpoint_outside_the_canonical_gitee_raw_manifest() {
    let temp = create_trust_root_fixture();

    let run = || {
        run_powershell(
            "scripts/test-update-trust-root.ps1",
            &[Path::new("-RepositoryRoot"), temp.path()],
        )
    };
    assert!(run().status.success(), "canonical Gitee endpoint must pass");
    for endpoint in [
        "https://gitee.com/another/repository/raw/main/latest.md",
        "https://gitcode.com/ericyin99/GPTEasy-Releases/raw/main/latest.md",
    ] {
        fs::write(
            temp.path().join("src-tauri/tauri.conf.json"),
            serde_json::to_vec_pretty(&json!({
                "bundle": { "createUpdaterArtifacts": true },
                "plugins": { "updater": { "endpoints": [endpoint], "pubkey": PUBLIC_KEY } }
            }))
            .expect("invalid Tauri trust root JSON"),
        )
        .expect("write invalid Tauri trust root");
        assert!(
            !run().status.success(),
            "accepted untrusted endpoint {endpoint}"
        );
    }
    fs::write(
        temp.path().join("src-tauri/tauri.conf.json"),
        serde_json::to_vec_pretty(&json!({
            "bundle": { "createUpdaterArtifacts": true },
            "plugins": { "updater": { "endpoints": [
                "https://gitee.com/ericshaohua/gpteasy-releases/raw/main/latest.md",
                "https://gitee.com/ericshaohua/gpteasy-releases/raw/main/fallback.md"
            ], "pubkey": PUBLIC_KEY } }
        }))
        .expect("multi-endpoint Tauri trust root JSON"),
    )
    .expect("write multi-endpoint Tauri trust root");
    assert!(
        !run().status.success(),
        "accepted multiple updater endpoints"
    );
}

#[test]
fn configure_trust_root_writes_only_public_endpoint_and_key() {
    let temp = TempDir::new().expect("configuration fixture");
    fs::create_dir_all(temp.path().join("src-tauri")).expect("create Tauri directory");
    fs::write(
        temp.path().join("src-tauri/tauri.conf.json"),
        serde_json::to_vec_pretty(&json!({
            "productName": "fixture",
            "bundle": { "active": true }
        }))
        .expect("Tauri fixture JSON"),
    )
    .expect("write Tauri fixture");
    let output = Command::new("node")
        .arg(repository_root().join("scripts/configure-update-trust-root.mjs"))
        .args(["example/releases", PUBLIC_KEY, "--repository-root"])
        .arg(temp.path())
        .output()
        .expect("configure update trust root");
    assert!(
        output.status.success(),
        "trust root configuration failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let config = read_json(temp.path().join("src-tauri/tauri.conf.json"));
    assert_eq!(config["bundle"]["createUpdaterArtifacts"], true);
    assert_eq!(config["plugins"]["updater"]["pubkey"], PUBLIC_KEY);
    assert_eq!(
        config["plugins"]["updater"]["endpoints"],
        json!(["https://gitee.com/example/releases/raw/main/latest.md"])
    );
    let serialized = serde_json::to_string(&config).expect("serialize configured trust root");
    assert!(!serialized.contains("GITEE_TOKEN"));
    assert!(!serialized.contains("PRIVATE_KEY"));
}

#[test]
fn configure_trust_root_accepts_the_current_tauri_public_key_header() {
    let temp = TempDir::new().expect("current Tauri public key fixture");
    fs::create_dir_all(temp.path().join("src-tauri")).expect("create Tauri directory");
    fs::write(
        temp.path().join("src-tauri/tauri.conf.json"),
        "{\"bundle\":{}}\n",
    )
    .expect("write Tauri config");
    let decoded = String::from_utf8(
        base64::engine::general_purpose::STANDARD
            .decode(PUBLIC_KEY)
            .expect("decode public key fixture"),
    )
    .expect("public key fixture UTF-8");
    let payload = decoded.lines().nth(1).expect("public key payload");
    let current_tauri_key = base64::engine::general_purpose::STANDARD.encode(format!(
        "untrusted comment: minisign public key: FIXTURE\n{payload}"
    ));
    let output = Command::new("node")
        .arg(repository_root().join("scripts/configure-update-trust-root.mjs"))
        .args(["example/releases", &current_tauri_key, "--repository-root"])
        .arg(temp.path())
        .output()
        .expect("configure current Tauri public key");
    assert!(
        output.status.success(),
        "current Tauri public key was rejected: {}",
        String::from_utf8_lossy(&output.stderr)
    );
}

#[test]
fn windows_candidate_requires_and_verifies_the_updater_signature() {
    let script = fs::read_to_string(repository_root().join("scripts/build-windows-candidate.ps1"))
        .expect("read Windows candidate builder");
    assert!(script.contains("TAURI_SIGNING_PRIVATE_KEY_PASSWORD"));
    assert!(script.contains("scripts/test-update-trust-root.ps1"));
    assert!(script.contains("verify_updater_signature"));
    assert!(script.contains("updaterSignature = 'passed'"));
    assert!(script.contains("signaturePath"));
    assert!(script.contains("$env:TAURI_SIGNING_PRIVATE_KEY = $resolvedSigningKey"));
    assert!(script.contains("Remove-Item Env:TAURI_SIGNING_PRIVATE_KEY"));
}

#[test]
fn encrypted_updater_key_check_understands_the_current_tauri_header() {
    let temp = TempDir::new().expect("updater key fixture");
    let encrypted = temp.path().join("encrypted.key");
    let unencrypted = temp.path().join("unencrypted.key");
    let encode = |value: &str| base64::engine::general_purpose::STANDARD.encode(value);
    fs::write(
        &encrypted,
        encode("untrusted comment: tauri signer encrypted secret key\nfixture-only\n"),
    )
    .expect("write encrypted key fixture");
    fs::write(
        &unencrypted,
        encode("untrusted comment: tauri signer secret key\nfixture-only\n"),
    )
    .expect("write unencrypted key fixture");

    let run = |path: &Path| {
        Command::new("node")
            .arg(repository_root().join("scripts/check-encrypted-updater-key.mjs"))
            .arg(path)
            .output()
            .expect("check encrypted updater key")
    };
    let encrypted_result = run(&encrypted);
    assert!(encrypted_result.status.success());
    let report: Value =
        serde_json::from_slice(&encrypted_result.stdout).expect("encrypted key report");
    assert_eq!(report, json!({ "encrypted": true }));
    assert!(!run(&unencrypted).status.success());
}

#[test]
fn repository_declares_repeatable_gitee_setup_without_formal_smoke_manifest_writes() {
    let root = repository_root();
    let wizard = fs::read_to_string(root.join("scripts/setup-gitee-distribution.sh"))
        .expect("read Gitee setup wizard");
    let contract = read_json(root.join("scripts/gitee-distribution.json"));
    let token_secret = contract["tokenSecret"].as_str().expect("token secret name");
    let repository_variable = contract["repositoryVariable"]
        .as_str()
        .expect("repository variable name");
    let branch_variable = contract["branchVariable"]
        .as_str()
        .expect("branch variable name");
    assert!(wizard.contains("ask_secret GITEE_TOKEN"));
    assert!(wizard.contains("set_secret \"$TOKEN_SECRET_NAME\""));
    assert!(wizard.contains("set_var \"$REPOSITORY_VARIABLE_NAME\""));
    assert!(wizard.contains("set_var \"$BRANCH_VARIABLE_NAME\""));
    assert!(wizard.contains("Gitee distribution repository must be public"));
    assert!(wizard.contains("anonymous Gitee README read failed"));
    assert_eq!(token_secret, "GITEE_TOKEN");
    assert_eq!(repository_variable, "GITEE_REPOSITORY");
    assert_eq!(branch_variable, "GITEE_DEFAULT_BRANCH");
    assert!(wizard.contains("离线备份"));
    assert!(wizard.contains("把 Gitee Token 保存到密码管理器"));
    assert_eq!(wizard.matches("ask_secret GITEE_TOKEN").count(), 1);
    assert!(wizard.contains("gh workflow run gitee-smoke.yml"));

    let operations = fs::read_to_string(root.join("docs/release/gitee-distribution.md"))
        .expect("read Gitee distribution operations");
    for required in [
        "scripts/cleanup-gitee-release.sh",
        "gh secret delete GITCODE_TOKEN",
        "gh variable delete GITCODE_REPOSITORY",
        "gh variable delete GITCODE_DEFAULT_BRANCH",
        "撤销 GitCode Token",
        "不删除 GitCode 公开仓库、Tag、历史 Release 或附件",
    ] {
        assert!(
            operations.contains(required),
            "Gitee migration operations miss {required}"
        );
    }

    let workflow = fs::read_to_string(root.join(".github/workflows/gitee-smoke.yml"))
        .expect("read Gitee smoke workflow");
    assert!(workflow.contains("GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}"));
    assert!(workflow.contains("GITEE_REPOSITORY: ${{ vars.GITEE_REPOSITORY }}"));

    let smoke = fs::read_to_string(root.join("scripts/smoke-gitee-release.sh"))
        .expect("read Gitee smoke command");
    assert!(smoke.contains("smoke-"));
    assert!(!smoke.contains("latest.md"));
}

#[test]
fn gitee_distribution_contract_contains_only_public_protocol_configuration() {
    let contract = read_json(repository_root().join("scripts/gitee-distribution.json"));
    assert_eq!(contract["schemaVersion"], 1);
    assert_eq!(contract["issue"], 55);
    assert_eq!(contract["apiBaseUrl"], "https://api.gitee.com/api/v5");
    assert_eq!(contract["rawBaseUrl"], "https://gitee.com");
    assert_eq!(contract["formalManifestPath"], "latest.md");
    assert_eq!(contract["smokeManifestPrefix"], "smoke/");
    assert_eq!(contract["platform"], "windows-x86_64");
    assert_eq!(contract["repositoryVariable"], "GITEE_REPOSITORY");
    assert_eq!(contract["branchVariable"], "GITEE_DEFAULT_BRANCH");
    assert_eq!(contract["tokenSecret"], "GITEE_TOKEN");
    let serialized = serde_json::to_string(&contract).expect("serialize Gitee contract");
    assert!(!serialized.contains("Bearer "));
    assert!(!serialized.contains("PRIVATE_KEY"));
    assert!(!serialized.contains("PASSWORD"));
}

#[test]
fn gitee_smoke_declares_authenticated_writes_and_anonymous_reads() {
    let smoke = fs::read_to_string(repository_root().join("scripts/smoke-gitee-release.sh"))
        .expect("read Gitee smoke command");
    assert!(smoke.contains("Authorization: Bearer $GITEE_TOKEN"));
    assert!(smoke.contains("--form \"file=@$CURL_ASSET_PATH"));
    assert!(smoke.contains("--range 0-0"));
    assert!(smoke.contains("prerelease=true"));

    #[derive(Debug)]
    struct RequestRecord {
        method: String,
        path: String,
        authorization: Option<String>,
    }

    let listener = TcpListener::bind("127.0.0.1:0").expect("bind fake Gitee server");
    let address = listener.local_addr().expect("fake Gitee address");
    let fixture = "GPTEasy Gitee distribution smoke fixture\n".to_owned();
    let fixture_size = fixture.len();
    let fixture_sha256 = format!("{:x}", Sha256::digest(fixture.as_bytes()));
    let fixture_relative = PathBuf::from("src-tauri/target/gitee-smoke-fixture.txt");
    let fixture_for_bash = fixture_relative.to_string_lossy().replace('\\', "/");
    let fixture_path = repository_root().join(&fixture_relative);
    fs::write(&fixture_path, &fixture).expect("write smoke attachment fixture");
    let records = Arc::new(Mutex::new(Vec::<RequestRecord>::new()));
    let server_records = Arc::clone(&records);
    let server = thread::spawn(move || {
        let mut raw_manifest = String::new();
        let mut attachment_downloads = 0;
        let mut raw_downloads = 0;
        for _ in 0..8 {
            let (mut stream, _) = listener.accept().expect("accept fake Gitee request");
            let mut request = Vec::new();
            let mut buffer = [0_u8; 8192];
            let header_end;
            loop {
                let read = stream.read(&mut buffer).expect("read fake request");
                assert!(read > 0, "request closed before headers");
                request.extend_from_slice(&buffer[..read]);
                if let Some(index) = request.windows(4).position(|window| window == b"\r\n\r\n") {
                    header_end = index + 4;
                    break;
                }
            }
            let headers = String::from_utf8_lossy(&request[..header_end]).into_owned();
            let content_length = headers
                .lines()
                .find_map(|line| {
                    line.strip_prefix("Content-Length: ")
                        .or_else(|| line.strip_prefix("content-length: "))
                })
                .and_then(|value| value.trim().parse::<usize>().ok())
                .unwrap_or(0);
            while request.len() < header_end + content_length {
                let read = stream.read(&mut buffer).expect("read fake request body");
                assert!(read > 0, "request closed before body");
                request.extend_from_slice(&buffer[..read]);
            }
            let request_line = headers.lines().next().expect("request line");
            let mut request_parts = request_line.split_whitespace();
            let method = request_parts.next().expect("request method").to_owned();
            let path = request_parts.next().expect("request path").to_owned();
            let authorization = headers.lines().find_map(|line| {
                line.strip_prefix("Authorization: ")
                    .or_else(|| line.strip_prefix("authorization: "))
                    .map(str::to_owned)
            });
            server_records
                .lock()
                .expect("request records")
                .push(RequestRecord {
                    method: method.clone(),
                    path: path.clone(),
                    authorization,
                });

            let (status, content_type, response, extra_headers) = if method == "POST"
                && path.ends_with("/releases")
            {
                (
                    201,
                    "application/json",
                    "{\"id\":42}".to_owned(),
                    String::new(),
                )
            } else if method == "POST" && path.ends_with("/releases/42/attach_files") {
                (
                    201,
                    "application/json",
                    "{\"id\":7}".to_owned(),
                    String::new(),
                )
            } else if method == "GET" && path.ends_with("/download") {
                attachment_downloads += 1;
                if attachment_downloads == 1 {
                    (
                        206,
                        "text/plain",
                        fixture[..1].to_owned(),
                        format!("Content-Range: bytes 0-0/{}\r\n", fixture.len()),
                    )
                } else {
                    (200, "text/plain", fixture.clone(), String::new())
                }
            } else if method == "POST" && path.contains("/contents/smoke/") {
                let body = &request[header_end..header_end + content_length];
                let body = String::from_utf8_lossy(body);
                let content = body
                    .split("name=\"content\"")
                    .nth(1)
                    .and_then(|value| value.split("\r\n\r\n").nth(1))
                    .and_then(|value| value.split("\r\n--").next())
                    .expect("content request form-data");
                let decoded = base64::engine::general_purpose::STANDARD
                    .decode(content)
                    .expect("decode test manifest");
                raw_manifest = String::from_utf8(decoded).expect("test manifest UTF-8");
                (201, "application/json", "{}".to_owned(), String::new())
            } else if method == "GET"
                && path.contains("/contents/smoke/")
                && path.ends_with("?ref=main")
            {
                (
                    200,
                    "application/json",
                    format!(
                        "{{\"download_url\":\"http://{address}/raw/blobs/fixture/smoke/smoke-42-1.md\"}}"
                    ),
                    String::new(),
                )
            } else if method == "GET" && path.starts_with("/raw/blobs/") {
                raw_downloads += 1;
                if raw_downloads == 1 {
                    (
                        403,
                        "text/plain",
                        "not propagated".to_owned(),
                        String::new(),
                    )
                } else {
                    (200, "application/json", raw_manifest.clone(), String::new())
                }
            } else {
                (
                    404,
                    "application/json",
                    "{\"message\":\"not found\"}".to_owned(),
                    String::new(),
                )
            };
            let reason = match status {
                200 => "OK",
                206 => "Partial Content",
                201 => "Created",
                403 => "Forbidden",
                418 => "I'm a teapot",
                _ => "Not Found",
            };
            write!(
                stream,
                "HTTP/1.1 {status} {reason}\r\nContent-Type: {content_type}\r\nContent-Length: {}\r\n{extra_headers}Connection: close\r\n\r\n{response}",
                response.len()
            )
            .expect("write fake response");
        }
    });

    let output = Command::new(git_bash())
        .arg("scripts/smoke-gitee-release.sh")
        .env("GITEE_TOKEN", "test-token")
        .env("GITEE_REPOSITORY", "example/releases")
        .env("GITEE_DEFAULT_BRANCH", "main")
        .env("SMOKE_RUN_ID", "42-1")
        .env("GITEE_SMOKE_TEST_MODE", "1")
        .env("SMOKE_ASSET_PATH", fixture_for_bash)
        .env("GITEE_API_BASE_URL", format!("http://{address}/api/v5"))
        .env("GITEE_RAW_BASE_URL", format!("http://{address}/raw"))
        .env("GITEE_SMOKE_RETRY_DELAY_SECONDS", "0")
        .current_dir(repository_root())
        .output()
        .expect("run Gitee smoke against fake server");
    assert!(
        output.status.success(),
        "Gitee smoke failed: {}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    server.join().expect("fake Gitee server");
    fs::remove_file(&fixture_path).expect("remove smoke attachment fixture");
    let report: Value = serde_json::from_slice(&output.stdout).expect("smoke report JSON");
    assert_eq!(report["passed"], true);
    assert_eq!(report["formalManifestAdvanced"], false);
    assert_eq!(report["tag"], "smoke-42-1");
    assert_eq!(report["releaseId"], 42);
    assert_eq!(
        report["anonymousRange"],
        json!({
            "status": 206,
            "bytes": 1,
            "contentRange": format!("bytes 0-0/{fixture_size}")
        })
    );
    assert_eq!(
        report["anonymousFullDownload"],
        json!({
            "size": fixture_size,
            "sha256": fixture_sha256
        })
    );

    let records = records.lock().expect("read request records");
    assert_eq!(records.len(), 8);
    assert!(
        records
            .iter()
            .all(|record| !record.path.contains("latest.md"))
    );
    for record in records.iter() {
        let authenticated = record.path.starts_with("/api/v5/")
            && !record.path.ends_with("/download")
            && !(record.method == "GET" && record.path.contains("/contents/smoke/"));
        if authenticated {
            assert_eq!(record.authorization.as_deref(), Some("Bearer test-token"));
        } else {
            assert_eq!(record.authorization, None);
        }
    }
    assert_eq!(records[0].method, "POST");
    assert_eq!(records[1].method, "POST");
    assert_eq!(records[7].method, "GET");
}

#[test]
fn gitee_smoke_cleanup_removes_the_exact_manifest_before_the_release() {
    #[derive(Debug)]
    struct RequestRecord {
        method: String,
        path: String,
        authorization: Option<String>,
        body: String,
    }

    let listener = TcpListener::bind("127.0.0.1:0").expect("bind fake Gitee server");
    listener
        .set_nonblocking(true)
        .expect("make fake Gitee server nonblocking");
    let address = listener.local_addr().expect("fake Gitee address");
    let records = Arc::new(Mutex::new(Vec::<RequestRecord>::new()));
    let server_records = Arc::clone(&records);
    let server = thread::spawn(move || {
        let mut last_request = Instant::now();
        let mut received_request = false;
        loop {
            let (mut stream, _) = match listener.accept() {
                Ok(connection) => connection,
                Err(error) if error.kind() == std::io::ErrorKind::WouldBlock => {
                    let idle_budget = if received_request {
                        Duration::from_millis(500)
                    } else {
                        Duration::from_secs(10)
                    };
                    if last_request.elapsed() > idle_budget {
                        break;
                    }
                    thread::sleep(Duration::from_millis(10));
                    continue;
                }
                Err(error) => panic!("accept fake Gitee request: {error}"),
            };
            last_request = Instant::now();
            received_request = true;
            stream
                .set_nonblocking(false)
                .expect("make accepted Gitee connection blocking");
            let mut request = Vec::new();
            let mut buffer = [0_u8; 8192];
            let header_end;
            loop {
                let read = stream.read(&mut buffer).expect("read fake request");
                assert!(read > 0, "request closed before headers");
                request.extend_from_slice(&buffer[..read]);
                if let Some(index) = request.windows(4).position(|window| window == b"\r\n\r\n") {
                    header_end = index + 4;
                    break;
                }
            }
            let headers = String::from_utf8_lossy(&request[..header_end]).into_owned();
            let content_length = headers
                .lines()
                .find_map(|line| {
                    line.strip_prefix("Content-Length: ")
                        .or_else(|| line.strip_prefix("content-length: "))
                })
                .and_then(|value| value.trim().parse::<usize>().ok())
                .unwrap_or(0);
            while request.len() < header_end + content_length {
                let read = stream.read(&mut buffer).expect("read fake request body");
                assert!(read > 0, "request closed before body");
                request.extend_from_slice(&buffer[..read]);
            }
            let request_line = headers.lines().next().expect("request line");
            let mut request_parts = request_line.split_whitespace();
            let method = request_parts.next().expect("request method").to_owned();
            let path = request_parts.next().expect("request path").to_owned();
            let authorization = headers.lines().find_map(|line| {
                line.strip_prefix("Authorization: ")
                    .or_else(|| line.strip_prefix("authorization: "))
                    .map(str::to_owned)
            });
            let body = String::from_utf8_lossy(&request[header_end..header_end + content_length])
                .into_owned();
            server_records
                .lock()
                .expect("request records")
                .push(RequestRecord {
                    method: method.clone(),
                    path: path.clone(),
                    authorization,
                    body,
                });

            let manifest = base64::engine::general_purpose::STANDARD.encode(
                r#"{"schemaVersion":1,"kind":"gitee-api-smoke","tag":"smoke-42-1","asset":"fixture.bin","sha256":"abc"}"#,
            );
            let (status, reason, response) = if method == "GET" && path.ends_with("/releases/42") {
                (200, "OK", r#"{"id":42,"tag_name":"smoke-42-1"}"#.to_owned())
            } else if method == "GET" && path.contains("/contents/smoke/smoke-42-1.md?ref=main") {
                (
                    200,
                    "OK",
                    format!(r#"{{"sha":"manifest-sha","content":"{manifest}"}}"#),
                )
            } else if method == "DELETE" && path.contains("/contents/smoke/smoke-42-1.md") {
                (204, "No Content", String::new())
            } else if method == "DELETE" && path.ends_with("/releases/42") {
                (204, "No Content", String::new())
            } else {
                (404, "Not Found", r#"{"message":"not found"}"#.to_owned())
            };
            write!(
                stream,
                "HTTP/1.1 {status} {reason}\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{response}",
                response.len()
            )
            .expect("write fake response");
        }
    });

    let mut child = Command::new(git_bash())
        .arg("scripts/cleanup-gitee-release.sh")
        .args(["42", "smoke-42-1"])
        .env("GITEE_TOKEN", "test-token")
        .env("GITEE_REPOSITORY", "example/releases")
        .env("GITEE_DEFAULT_BRANCH", "main")
        .env("GITEE_API_BASE_URL", format!("http://{address}/api/v5"))
        .current_dir(repository_root())
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("run Gitee smoke cleanup against fake server");
    child
        .stdin
        .as_mut()
        .expect("cleanup stdin")
        .write_all(b"smoke-42-1\n")
        .expect("confirm exact smoke tag");
    let output = child.wait_with_output().expect("wait for cleanup command");
    server.join().expect("fake Gitee server");
    assert!(
        output.status.success(),
        "Gitee cleanup failed: {}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );

    let records = records.lock().expect("read cleanup requests");
    let sequence = records
        .iter()
        .map(|record| format!("{} {}", record.method, record.path))
        .collect::<Vec<_>>();
    assert_eq!(
        sequence,
        vec![
            "GET /api/v5/repos/example/releases/releases/42",
            "GET /api/v5/repos/example/releases/contents/smoke/smoke-42-1.md?ref=main",
            "DELETE /api/v5/repos/example/releases/contents/smoke/smoke-42-1.md",
            "DELETE /api/v5/repos/example/releases/releases/42",
        ]
    );
    assert!(
        records
            .iter()
            .all(|record| { record.authorization.as_deref() == Some("Bearer test-token") })
    );
    let manifest_delete = &records[2].body;
    assert!(manifest_delete.contains("manifest-sha"));
    assert!(manifest_delete.contains("main"));
    assert!(manifest_delete.contains("smoke-42-1"));
}
