#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
VERSION="${1:-}"
[[ "$VERSION" =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$ ]] || {
  printf 'usage: bash scripts/manual-upload-gitee-installer.sh <stable-version>\n' >&2
  exit 2
}

TAG="v$VERSION"
GITHUB_REPOSITORY="yinshaohua/GPTEasy"
GITEE_REPOSITORY="ericshaohua/gpteasy-releases"
ASSET="GPTEasy_${VERSION}_x64-setup.exe"
WORKSPACE=$(mktemp -d)
trap 'rm -rf -- "$WORKSPACE"' EXIT
INSTALLER="$WORKSPACE/$ASSET"
VERIFIED="$WORKSPACE/verified-$ASSET"
EDIT_URL="https://gitee.com/$GITEE_REPOSITORY/releases/$TAG/edit"
DOWNLOAD_URL="https://gitee.com/$GITEE_REPOSITORY/releases/download/$TAG/$ASSET"

banner "GPTEasy Gitee installer upload"

stage "取得权威安装包"
say "从 GitHub 正式 Release 下载已经签名的构建产物，不在本机重建。"
command -v gh >/dev/null 2>&1 || { warn "gh CLI is required"; exit 1; }
command -v curl >/dev/null 2>&1 || { warn "curl is required"; exit 1; }
gh release download "$TAG" --repo "$GITHUB_REPOSITORY" --pattern "$ASSET" --dir "$WORKSPACE" --clobber
node scripts/gitee-smoke-json.mjs verify-pe "$INSTALLER" 1
INSTALLER_SHA=$(sha256sum "$INSTALLER" | awk '{print $1}')
DISPLAY_PATH="$INSTALLER"
if command -v cygpath >/dev/null 2>&1; then DISPLAY_PATH=$(cygpath -w "$INSTALLER"); fi
if command -v wslpath >/dev/null 2>&1; then DISPLAY_PATH=$(wslpath -w "$INSTALLER"); fi
say "文件：$DISPLAY_PATH"
say "SHA-256：$INSTALLER_SHA"
pause "确认已看到文件路径和哈希后按 Enter。"

stage "在 Gitee 网页上传"
open_url "$EDIT_URL"
step "在附件区域选择文件：$DISPLAY_PATH"
step "附件名必须保持为 $ASSET；不要改成 .bin，也不要上传本机重新构建的文件。"
step "若页面仍有 $ASSET.bin，请删除它。"
step "仅在 SHA256SUMS.txt 仍引用 .exe.bin 时删除该校验文件；保留 $ASSET.sig。"
step "等待上传完成并保存 Release。不要修改 Tag、标题或发布说明。"
confirm "已保存 Gitee Release，并确认页面列出标准 .exe 附件？" || {
  warn "尚未确认上传，自动同步不会触发。"
  exit 1
}

stage "匿名核对安装包"
say "使用无 Token、无 Cookie 的稳定 Release URL 下载并逐字节比较。"
downloaded=0
for attempt in $(seq 1 20); do
  if curl --fail --silent --show-error --location --output "$VERIFIED" "$DOWNLOAD_URL"; then
    downloaded=1
    break
  fi
  note "附件尚未公开，第 $attempt/20 次等待。"
  sleep 5
done
[[ "$downloaded" == 1 ]] || { warn "匿名下载在等待预算内仍不可用"; exit 1; }
cmp --silent "$INSTALLER" "$VERIFIED" || { warn "Gitee 附件与 GitHub Release 字节不一致"; exit 1; }
VERIFIED_SHA=$(sha256sum "$VERIFIED" | awk '{print $1}')
say "匿名下载通过：$VERIFIED_SHA"

stage "完成自动同步"
say "自动同步会复核 .exe、.sig 和 SHA256SUMS.txt，最后才更新 latest.md。"
confirm "现在触发 $TAG 的 Gitee 正式同步并等待结果？" || {
  warn "尚未触发同步；稍后运行 gh workflow run gitee-sync.yml -f tag=$TAG"
  exit 1
}
RUN_URL=$(gh workflow run gitee-sync.yml --repo "$GITHUB_REPOSITORY" -f "tag=$TAG")
say "工作流：$RUN_URL"
RUN_ID="${RUN_URL##*/}"
if [[ "$RUN_ID" =~ ^[0-9]+$ ]]; then
  gh run watch "$RUN_ID" --repo "$GITHUB_REPOSITORY" --exit-status
else
  warn "无法从输出取得 Run ID，请在 GitHub Actions 页面确认同步结果。"
  open_url "https://github.com/$GITHUB_REPOSITORY/actions/workflows/gitee-sync.yml"
  exit 1
fi

finish
