#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
[[ "$ENV_FILE" == ".env" ]] && ENV_FILE=".release.env"

CONTRACT_PATH="scripts/gitee-distribution.json"
config_value() {
  node scripts/gitee-smoke-json.mjs config "$CONTRACT_PATH" "$1"
}
REPOSITORY_VARIABLE_NAME=$(config_value repositoryVariable)
BRANCH_VARIABLE_NAME=$(config_value branchVariable)
TOKEN_SECRET_NAME=$(config_value tokenSecret)
CONTRACT_DEFAULT_BRANCH=$(config_value defaultBranch)

banner "GPTEasy Gitee 分发设置"

stage "创建公开分发仓库"
say "该仓库只保存下载说明、更新清单和 Release，不镜像源码，也不执行构建。"
open_url "https://gitee.com/new"
step "创建公开仓库；使用 main 作为默认分支，并用下载说明初始化 README。"
ask GITEE_REPOSITORY "输入公开仓库坐标（owner/repo）："
[[ "$GITEE_REPOSITORY" =~ ^[^/[:space:]]+/[^/[:space:]]+$ ]] || { warn "仓库坐标必须是 owner/repo"; exit 1; }
GITEE_DEFAULT_BRANCH="$CONTRACT_DEFAULT_BRANCH"
write_env GITEE_REPOSITORY "$GITEE_REPOSITORY"
write_env GITEE_DEFAULT_BRANCH "$GITEE_DEFAULT_BRANCH"

stage "创建最小权限 Token"
open_url "https://gitee.com/setting/token-classic"
step "创建仅能维护该公开仓库 Release 与仓库内容的 Token；不要授予账户管理权限。"
step "复制 Token。页面关闭后通常无法再次查看。"
ask_secret GITEE_TOKEN "粘贴 Gitee Token（输入不会显示）："
[[ -n "$GITEE_TOKEN" ]] || { warn "Token 不能为空"; exit 1; }
set_secret "$TOKEN_SECRET_NAME" "$GITEE_TOKEN"

stage "验证公开仓库"
say "正在验证仓库可匿名访问，且 main 已由 README 初始化。"
export GITEE_TOKEN
GITEE_REPOSITORY="$GITEE_REPOSITORY" GITEE_DEFAULT_BRANCH="$GITEE_DEFAULT_BRANCH" node --input-type=module <<'NODE'
const repository = process.env.GITEE_REPOSITORY;
const branch = process.env.GITEE_DEFAULT_BRANCH;
const token = process.env.GITEE_TOKEN;
const apiBase = "https://api.gitee.com/api/v5";

const response = await fetch(`${apiBase}/repos/${repository}`, {
  headers: { Accept: "application/json", Authorization: `Bearer ${token}` },
});
if (!response.ok) throw new Error(`Gitee repository lookup failed with HTTP ${response.status}`);
const details = await response.json();
if (details.private === true || details.public === false) throw new Error("Gitee distribution repository must be public");
if (details.default_branch !== branch) throw new Error(`Gitee default branch must be ${branch}`);
const readme = await fetch(`${apiBase}/repos/${repository}/contents/README.md?ref=${encodeURIComponent(branch)}`, {
  headers: { Accept: "application/json", Authorization: `Bearer ${token}` },
});
if (!readme.ok) throw new Error(`Gitee README on ${branch} is unavailable (HTTP ${readme.status})`);
const anonymous = await fetch(`https://gitee.com/${repository}/raw/${encodeURIComponent(branch)}/README.md`);
if (!anonymous.ok || !(await anonymous.text()).trim()) throw new Error("anonymous Gitee README read failed");
NODE
unset GITEE_TOKEN
set_var "$REPOSITORY_VARIABLE_NAME" "$GITEE_REPOSITORY"
set_var "$BRANCH_VARIABLE_NAME" "$GITEE_DEFAULT_BRANCH"

stage "生成 updater 信任根"
say "私钥必须留在仓库外。Tauri 将在终端中隐藏询问并确认密码。"
ask UPDATER_KEY_PATH "输入仓库外私钥路径（建议 ~/.tauri/gpteasy-updater.key）："
[[ -n "$UPDATER_KEY_PATH" ]] || UPDATER_KEY_PATH="$HOME/.tauri/gpteasy-updater.key"
UPDATER_KEY_PATH="${UPDATER_KEY_PATH/#\~/$HOME}"
mkdir -p "$(dirname "$UPDATER_KEY_PATH")"
if [[ ! -f "$UPDATER_KEY_PATH" ]]; then
  npx --no-install tauri signer generate --write-keys "$UPDATER_KEY_PATH"
else
  note "保留已有私钥：$UPDATER_KEY_PATH"
fi
[[ -s "$UPDATER_KEY_PATH" && -s "$UPDATER_KEY_PATH.pub" ]] || { warn "Tauri 未生成完整密钥对"; exit 1; }
if ! node scripts/check-encrypted-updater-key.mjs "$UPDATER_KEY_PATH" >/dev/null; then
  warn "私钥没有使用密码加密；请安全删除后重新生成"
  exit 1
fi
UPDATER_PUBLIC_KEY=$(tr -d '\r\n' < "$UPDATER_KEY_PATH.pub")
write_env UPDATER_KEY_PATH "$UPDATER_KEY_PATH"
write_env UPDATER_PUBLIC_KEY "$UPDATER_PUBLIC_KEY"
node scripts/configure-update-trust-root.mjs "$GITEE_REPOSITORY" "$UPDATER_PUBLIC_KEY"

stage "确认离线备份"
step "把私钥文件复制到至少一份离线加密介质。"
step "把密钥密码保存到与私钥分离的密码管理器或离线记录。"
confirm "已经验证离线备份可读取，并确认密码没有写入仓库或终端日志？" || {
  warn "离线备份确认前不能完成信任根设置"
  exit 1
}

stage "运行非正式 API 冒烟"
say "GitHub workflow 从 secret 读取 Token；本机不再保存或重复输入。"
confirm "工作流已经提交并推送到 GitHub main，立即触发真实冒烟？" || {
  SKIPPED+=("Gitee API smoke workflow")
  finish
  exit 0
}
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  gh workflow run gitee-smoke.yml
  sleep 3
  gh run watch --workflow gitee-smoke.yml --exit-status
else
  SKIPPED+=("Gitee API smoke workflow (run: gh workflow run gitee-smoke.yml)")
  warn "gh 未就绪，未运行冒烟工作流"
fi

finish
